//! One `cmux-tui` command line per safe catalog operation, with the
//! operation it sends: the CLI's coverage test and `cmux mcp`'s parity test
//! both read it.

pub(in crate::cli) fn safe_operation_cases() -> Vec<(Vec<&'static str>, &'static str)> {
    const MACHINE: &str = "machine_00000000000000000000000000000001";
    const SESSION: &str = "session_00000000000000000000000000000002";
    const CLIENT: &str = "client_00000000000000000000000000000003";
    const WORKSPACE: &str = "ws_00000000000000000000000000000004";
    const SCREEN: &str = "screen_00000000000000000000000000000005";
    const PANE: &str = "pane_00000000000000000000000000000006";
    const TAB: &str = "tab_00000000000000000000000000000007";
    const TERMINAL: &str = "term_00000000000000000000000000000008";
    const BROWSER: &str = "browser_00000000000000000000000000000009";
    const PAIRING: &str = "pairing_0000000000000000000000000000000b";
    const PROJECTION: &str = "projection_0000000000000000000000000000000c";
    const VIEW: &str = "sidebar_view_0000000000000000000000000000000d";
    const CHECKPOINT: &str = "ckpt_0000000000000000000000000000000e";

    let mut cases: Vec<(Vec<&'static str>, &'static str)> = vec![
        (vec!["machine", "list"], "machine.list"),
        (vec!["machine", MACHINE, "show"], "machine.get"),
        (vec!["machine", MACHINE, "session", "list"], "session.list"),
        (vec!["machine", MACHINE, "session", SESSION, "open"], "session.open"),
        (vec!["session", SESSION, "show"], "session.get"),
        (vec!["session", SESSION, "snapshot"], "session.snapshot"),
        (vec!["session", SESSION, "creation", "create-42", "resolve"], "session.creation.resolve"),
        (
            vec!["session", SESSION, "events", "--generation", "g1", "--revision", "3"],
            "session.events",
        ),
        (
            vec![
                "session",
                SESSION,
                "journal",
                "read",
                "--from",
                "beginning",
                "--kinds",
                "pane.*,tab.focus",
            ],
            "session.journal.subscribe",
        ),
        (vec!["session", SESSION, "journal", "producer", "list"], "session.journal.producer.list"),
        (
            vec![
                "session",
                SESSION,
                "journal",
                "producer",
                "put",
                "--manifest-json",
                r#"{"producer_id":"demo","namespace":"plugin.demo"}"#,
            ],
            "session.journal.producer.put",
        ),
        (
            vec![
                "session",
                SESSION,
                "journal",
                "append",
                "--event-json",
                r#"{"producer_id":"demo","payload":{"ready":true}}"#,
            ],
            "session.journal.append",
        ),
        (vec!["session", SESSION, "journal", "hook", "list"], "session.journal.hook.list"),
        (
            vec![
                "session",
                SESSION,
                "journal",
                "hook",
                "put",
                "--manifest-json",
                r#"{"hook_id":"demo_hook","manifest_version":1}"#,
            ],
            "session.journal.hook.put",
        ),
        (
            vec!["session", SESSION, "journal", "checkpoint", "create"],
            "session.journal.checkpoint.create",
        ),
        (
            vec!["session", SESSION, "journal", "checkpoint", "list"],
            "session.journal.checkpoint.list",
        ),
        (
            vec!["session", SESSION, "journal", "restore", "preview", "--checkpoint", "latest"],
            "session.journal.restore.preview",
        ),
        (vec!["session", SESSION, "journal", "segment", "list"], "session.journal.segment.list"),
        (
            vec!["session", SESSION, "journal", "segment", "seal", "--through", "42"],
            "session.journal.segment.seal",
        ),
        (vec!["session", SESSION, "ping"], "session.ping"),
        (vec!["session", SESSION, "shutdown", "--force"], "session.shutdown"),
        (vec!["session", SESSION, "config", "reload"], "session.reload_config"),
        (
            vec![
                "session",
                SESSION,
                "terminal",
                "defaults",
                "set",
                "--foreground",
                "#ffffff",
                "--background",
                "#000000",
                "--cursor",
                "#aaaaaa",
                "--selection-background",
                "#111111",
                "--selection-foreground",
                "#eeeeee",
                "--cursor-style",
                "bar",
                "--cursor-blink",
                "true",
                "--palette",
                "{\"0\":\"#000000\",\"255\":\"#ffffff\"}",
                "--complete",
            ],
            "session.terminal_defaults.update",
        ),
        (vec!["client", "list"], "client.list"),
        (vec!["client", CLIENT, "show"], "client.get"),
        (
            vec!["client", CLIENT, "metadata", "set", "--name", "cli", "--kind", "automation"],
            "client.metadata.update",
        ),
        (
            vec![
                "client",
                CLIENT,
                "sizing",
                "set",
                "--terminal",
                TERMINAL,
                "--enabled",
                "true",
                "--exclusive",
                "true",
            ],
            "client.sizing.set",
        ),
        (
            vec!["client", CLIENT, "sizing", "release", "--terminal", TERMINAL],
            "client.sizing.release",
        ),
        (
            vec!["client", CLIENT, "cell", "pixels", "set", "--width-px", "8", "--height-px", "16"],
            "client.cell_pixels.set",
        ),
        (vec!["client", CLIENT, "detach"], "client.detach"),
        (
            vec!["session", SESSION, "window", "title", "set", "--title", "build"],
            "session.window.title.set",
        ),
        (vec!["session", SESSION, "window", "title", "clear"], "session.window.title.clear"),
        (vec!["pairing", "request", "list"], "pairing_request.list"),
        (vec!["pairing", "request", PAIRING, "respond", "accept"], "pairing_request.resolve"),
        (vec!["projection", PROJECTION, "show"], "frontend_projection.get"),
        (
            vec![
                "projection",
                PROJECTION,
                "put",
                "--projection",
                "{\"sidebar\":\"compact\"}",
                "--frontend-id",
                "cmux-cli",
                "--window-id",
                "window-1",
                "--generation",
                "launch-1",
                "--expected-projection-revision",
                "7",
            ],
            "frontend_projection.put",
        ),
        (vec!["workspace", "list"], "workspace.list"),
        (vec!["workspace", WORKSPACE, "show"], "workspace.get"),
        (
            vec![
                "workspace",
                "create",
                "--empty",
                "--ephemeral",
                "--name",
                "empty",
                "--correlation-key",
                "create-42",
            ],
            "workspace.create",
        ),
        (vec!["workspace", WORKSPACE, "rename", "--name", "api"], "workspace.rename"),
        (vec!["workspace", WORKSPACE, "move", "--index", "2"], "workspace.move"),
        (vec!["workspace", WORKSPACE, "focus"], "workspace.focus"),
        (vec!["workspace", WORKSPACE, "close"], "workspace.close"),
        (
            vec![
                "workspace",
                WORKSPACE,
                "run",
                "--cwd",
                "/tmp",
                "--name",
                "tests",
                "--cols",
                "100",
                "--rows",
                "40",
                "--on-exit",
                "keep",
                "--correlation-key",
                "create-42",
                "--",
                "cargo",
                "test",
            ],
            "workspace.run",
        ),
        (
            vec!["workspace", WORKSPACE, "layout", "apply", "--layout", "{\"kind\":\"leaf\"}"],
            "workspace.layout.apply",
        ),
        (vec!["screen", "list"], "screen.list"),
        (vec!["screen", SCREEN, "show"], "screen.get"),
        (
            vec!["screen", "create", "--name", "build", "--correlation-key", "create-42"],
            "screen.create",
        ),
        (vec!["screen", SCREEN, "rename", "--name", "tests"], "screen.rename"),
        (vec!["screen", SCREEN, "focus"], "screen.focus"),
        (vec!["screen", SCREEN, "close"], "screen.close"),
        (vec!["screen", SCREEN, "layout", "export"], "screen.layout.export"),
        (
            vec![
                "screen",
                SCREEN,
                "layout",
                "undo",
                "--confirm-close",
                "--confirmation-token",
                "layout-preview-token",
            ],
            "screen.layout.undo",
        ),
        (
            vec![
                "screen",
                SCREEN,
                "column",
                "split_00000000000000000000000000000011",
                "update",
                "--sticky",
                "true",
                "--edge",
                "left",
                "--mode",
                "overlay",
                "--width",
                "0.5",
            ],
            "column.update",
        ),
        (vec!["pane", "list"], "pane.list"),
        (vec!["pane", PANE, "show"], "pane.get"),
        (
            vec![
                "pane",
                "create",
                "--cwd",
                "/tmp",
                "--cols",
                "80",
                "--rows",
                "24",
                "--correlation-key",
                "create-42",
            ],
            "pane.create",
        ),
        (
            vec![
                "pane",
                PANE,
                "split",
                "--right",
                "--ratio",
                "0.5",
                "--viewport-width",
                "0.5",
                "--cwd",
                "/tmp",
                "--cols",
                "80",
                "--rows",
                "24",
                "--correlation-key",
                "create-42",
            ],
            "pane.split",
        ),
        (vec!["pane", PANE, "rename", "--name", "server"], "pane.rename"),
        (vec!["pane", PANE, "focus"], "pane.focus"),
        (vec!["pane", PANE, "focus", "direction", "right"], "pane.focus_direction"),
        (vec!["pane", PANE, "neighbor", "left"], "pane.neighbor.get"),
        (
            vec![
                "pane",
                PANE,
                "swap",
                "--other-workspace",
                WORKSPACE,
                "--other-screen",
                SCREEN,
                "--other-pane",
                PANE,
            ],
            "pane.swap",
        ),
        (vec!["pane", PANE, "zoom", "--enabled", "true"], "pane.zoom"),
        (
            vec![
                "pane",
                PANE,
                "split",
                "ratio",
                "set",
                "--split",
                "split_0000000000000000000000000000000f",
                "--ratio",
                "0.5",
            ],
            "pane.split_ratio.set",
        ),
        (
            vec!["pane", PANE, "viewport", "width", "set", "--columns", "80"],
            "pane.viewport_width.set",
        ),
        (vec!["pane", PANE, "close"], "pane.close"),
        (
            vec![
                "pane",
                PANE,
                "run",
                "--cwd",
                "/tmp",
                "--name",
                "make",
                "--cols",
                "90",
                "--rows",
                "30",
                "--on-exit",
                "keep",
                "--correlation-key",
                "create-42",
                "--",
                "make",
                "test",
            ],
            "pane.run",
        ),
        (vec!["tab", "list"], "tab.list"),
        (vec!["tab", TAB, "show"], "tab.get"),
        (
            vec![
                "tab",
                "create",
                "terminal",
                "--cwd",
                "/tmp",
                "--name",
                "shell",
                "--cols",
                "80",
                "--rows",
                "24",
                "--correlation-key",
                "create-42",
            ],
            "tab.create_terminal",
        ),
        (
            vec![
                "tab",
                "create",
                "browser",
                "--url",
                "https://example.com",
                "--name",
                "docs",
                "--width-px",
                "1200",
                "--height-px",
                "800",
                "--correlation-key",
                "create-42",
            ],
            "tab.create_browser",
        ),
        (
            vec![
                "tab",
                TAB,
                "rename",
                "--name",
                "logs",
                "--source",
                "auto",
                "--expected-generation",
                "daemon",
                "--expected-name-revision",
                "0",
            ],
            "tab.rename",
        ),
        (
            vec![
                "tab",
                TAB,
                "move",
                "--workspace",
                WORKSPACE,
                "--screen",
                SCREEN,
                "--pane",
                PANE,
                "--index",
                "0",
            ],
            "tab.move",
        ),
        (vec!["tab", TAB, "focus"], "tab.focus"),
        (vec!["tab", TAB, "close"], "tab.close"),
        (vec!["terminal", "list"], "terminal.list"),
        (vec!["terminal", TERMINAL, "show"], "terminal.get"),
        (vec!["terminal", TERMINAL, "write", "--text", "hello"], "terminal.input.write"),
        (vec!["terminal", TERMINAL, "keys", "ctrl-c"], "terminal.input.keys"),
        (
            vec![
                "terminal",
                TERMINAL,
                "mouse",
                "down",
                "--row",
                "4",
                "--column",
                "7",
                "--button",
                "left",
                "--modifiers",
                "shift,meta",
            ],
            "terminal.input.mouse",
        ),
        (vec!["terminal", TERMINAL, "focus", "in"], "terminal.input.focus"),
        (vec!["terminal", TERMINAL, "screen", "read"], "terminal.screen.read"),
        (vec!["terminal", TERMINAL, "state", "read"], "terminal.state.read"),
        (
            vec![
                "terminal", TERMINAL, "history", "read", "--before", "0", "--limit", "100",
                "--styled",
            ],
            "terminal.history.read",
        ),
        (vec!["terminal", TERMINAL, "history", "clear"], "terminal.history.clear"),
        (
            vec!["terminal", TERMINAL, "output", "read", "--after", "4096", "--max-bytes", "65536"],
            "terminal.output_read",
        ),
        (
            vec![
                "terminal",
                TERMINAL,
                "screen",
                "wait",
                "--pattern",
                "ready",
                "--timeout-ms",
                "5000",
            ],
            "terminal.wait",
        ),
        (vec!["terminal", TERMINAL, "copy", "--mode", "screen"], "terminal.copy"),
        (vec!["terminal", TERMINAL, "process", "show"], "terminal.process.get"),
        (
            vec!["terminal", TERMINAL, "process", "wait", "--timeout-ms", "5000"],
            "terminal.wait_exit",
        ),
        (
            vec!["terminal", TERMINAL, "viewport", "scroll", "--delta-rows", "-3"],
            "terminal.viewport.scroll",
        ),
        (
            vec![
                "terminal",
                TERMINAL,
                "move",
                "--workspace",
                WORKSPACE,
                "--screen",
                SCREEN,
                "--pane",
                PANE,
                "--index",
                "1",
            ],
            "terminal.move",
        ),
        (
            vec![
                "terminal",
                TERMINAL,
                "project",
                "--workspace",
                WORKSPACE,
                "--screen",
                SCREEN,
                "--pane",
                PANE,
                "--index",
                "1",
                "--name",
                "mirror",
            ],
            "terminal.project",
        ),
        (
            vec!["terminal", TERMINAL, "attach", "--cols", "100", "--rows", "40", "--read-only"],
            "terminal.attach",
        ),
        (vec!["terminal", TERMINAL, "close"], "terminal.close"),
        (vec!["browser", "list"], "browser.list"),
        (vec!["browser", BROWSER, "show"], "browser.get"),
        (vec!["browser", BROWSER, "navigate", "--url", "https://example.com"], "browser.navigate"),
        (vec!["browser", BROWSER, "back"], "browser.back"),
        (vec!["browser", BROWSER, "forward"], "browser.forward"),
        (vec!["browser", BROWSER, "reload"], "browser.reload"),
        (vec!["browser", BROWSER, "activate"], "browser.activate"),
        (
            vec![
                "browser",
                BROWSER,
                "key",
                "--key",
                "Enter",
                "--kind",
                "press",
                "--modifiers",
                "shift,meta",
            ],
            "browser.input.key",
        ),
        (vec!["browser", BROWSER, "text", "--text", "hello"], "browser.input.text"),
        (
            vec![
                "browser",
                BROWSER,
                "mouse",
                "--kind",
                "down",
                "--x-px",
                "10",
                "--y-px",
                "20",
                "--button",
                "left",
                "--click-count",
                "2",
                "--pointer-frame-seq",
                "42",
            ],
            "browser.input.mouse",
        ),
        (
            vec![
                "browser",
                BROWSER,
                "wheel",
                "--delta-x",
                "1",
                "--delta-y",
                "120",
                "--x-px",
                "10",
                "--y-px",
                "20",
                "--pointer-frame-seq",
                "42",
            ],
            "browser.input.wheel",
        ),
        (
            vec!["browser", BROWSER, "attach", "--width-px", "1200", "--height-px", "800"],
            "browser.attach",
        ),
        (vec!["browser", BROWSER, "close"], "browser.close"),
        (vec!["notification", "list", "--limit", "100"], "notification.list"),
        (
            vec![
                "notification",
                "create",
                "--subtitle",
                "api",
                "--title",
                "done",
                "--body",
                "tests passed",
                "--level",
                "success",
                "--terminal",
                TERMINAL,
            ],
            "notification.create",
        ),
        (vec!["agent", "list", "--terminal", TERMINAL, "--state", "working"], "agent.list"),
        (
            vec![
                "agent",
                "report",
                "--terminal",
                TERMINAL,
                "--state",
                "working",
                "--source",
                "socket",
                "--source-session",
                "job-1",
            ],
            "agent.report",
        ),
        (vec!["sidebar", "view", "show", "--view", VIEW], "sidebar_view.get"),
        (
            vec!["sidebar", "view", "ensure", "--cols", "30", "--rows", "40", "--relaunch"],
            "sidebar_view.ensure",
        ),
        (vec!["sidebar", "view", "attach", "--view", VIEW], "sidebar_view.attach"),
        (vec!["sidebar", "view", "input", "--view", VIEW, "--text", "j"], "sidebar_view.input"),
        (
            vec!["sidebar", "view", "resize", "--view", VIEW, "--cols", "30", "--rows", "40"],
            "sidebar_view.resize",
        ),
        (vec!["sidebar", "view", "reload", "--view", VIEW], "sidebar_view.reload"),
        (
            vec![
                "notification",
                "ack",
                "notification_00000000000000000000000000000041",
                "--client",
                "mac-1",
            ],
            "notification.ack",
        ),
        (
            vec!["notification", "clear", "--terminal", "term_00000000000000000000000000000041"],
            "notification.clear",
        ),
        (vec!["git", "status", "--path", "/repo"], "git.status"),
        (
            vec!["git", "files", "--path", "/repo", "--limit", "20", "app", "tsx"],
            "git.files.search",
        ),
        (
            vec![
                "git",
                "checkpoint",
                "diff",
                "--path",
                "/repo",
                "ckpt_00000000000000000000000000000001",
                "ckpt_00000000000000000000000000000002",
                "--only",
                "src,docs",
                "--patch",
                "--max-patch-bytes",
                "1024",
                "--max-files",
                "10",
            ],
            "git.checkpoint.diff",
        ),
        (
            vec![
                "git",
                "diff",
                "--path",
                "/repo",
                "--scope",
                "staged",
                "--patch",
                "--max-patch-bytes",
                "1024",
                "--max-files",
                "10",
                "src",
            ],
            "git.diff",
        ),
        (
            vec![
                "git",
                "checkpoint",
                "create",
                "--path",
                "/repo",
                "--reason",
                "handoff",
                "--exclude",
                "target,.env.local",
                "--expected-repository",
                "repo_00000000000000000000000000000001",
                "--expected-worktree",
                "wt_00000000000000000000000000000001",
                "--max-bytes",
                "1048576",
                "--max-files",
                "100",
                "notes.md",
            ],
            "git.checkpoint.create",
        ),
        (vec!["git", "checkpoint", "get", CHECKPOINT, "--path", "/repo"], "git.checkpoint.get"),
        (
            vec![
                "git",
                "checkpoint",
                "list",
                "--path",
                "/repo",
                "--cursor",
                "1.ckpt_1",
                "--limit",
                "10",
                "--candidates",
            ],
            "git.checkpoint.list",
        ),
        (
            vec!["git", "checkpoint", "pin", CHECKPOINT, "--pin", "user:keep", "--reason", "keep"],
            "git.checkpoint.pin",
        ),
        (
            vec!["git", "checkpoint", "unpin", CHECKPOINT, "--pin", "user:keep"],
            "git.checkpoint.unpin",
        ),
    ];
    cases.extend(state_resource_cases(WORKSPACE, SCREEN, PANE, TAB));
    cases
}

/// One path per state resource operation (state-ownership.md steps A
/// and B), exercising every catalog field.
fn state_resource_cases<'a>(
    workspace: &'a str,
    screen: &'a str,
    pane: &'a str,
    tab: &'a str,
) -> Vec<(Vec<&'a str>, &'a str)> {
    vec![
        (
            vec![
                "workspace",
                workspace,
                "update",
                "--title",
                "T",
                "--color",
                "red",
                "--icon",
                "star",
            ],
            "workspace.update",
        ),
        (
            vec!["workspace", "group", "g", "add", "--workspace", workspace, "--index", "0"],
            "workspace.place",
        ),
        (vec!["workspace", "placement", "list"], "workspace.placement.list"),
        (vec!["workspace", "group", "list", "--room", "r"], "workspace_group.list"),
        (
            vec![
                "workspace",
                "group",
                "create",
                "--name",
                "n",
                "--color",
                "blue",
                "--room",
                "r",
                "--index",
                "0",
                "--collapse",
            ],
            "workspace_group.create",
        ),
        (
            vec![
                "workspace",
                "group",
                "g",
                "update",
                "--name",
                "n",
                "--color",
                "red",
                "--room",
                "r",
                "--collapse",
            ],
            "workspace_group.update",
        ),
        (vec!["workspace", "group", "g", "delete"], "workspace_group.delete"),
        (vec!["workspace", "group", "g", "move", "--index", "1"], "workspace_group.move"),
        (vec!["tab", tab, "pin"], "tab.pin"),
        (vec!["tab", tab, "unpin"], "tab.unpin"),
        (vec!["tab", tab, "update", "--zoom", "1.5"], "tab.update"),
        (vec!["tab", "group", "list", "--pane", pane], "tab_group.list"),
        (vec!["tab", "group", "g", "show"], "tab_group.get"),
        (
            vec!["tab", "group", "create", "--tabs", tab, "--name", "n", "--color", "green"],
            "tab_group.create",
        ),
        (
            vec!["tab", "group", "g", "update", "--name", "n", "--color", "red", "--collapse"],
            "tab_group.update",
        ),
        (vec!["tab", "group", "g", "add", "--tabs", tab, "--index", "0"], "tab_group.add_tabs"),
        (vec!["tab", "group", "remove", "--tabs", tab], "tab_group.remove_tabs"),
        (vec!["tab", "group", "g", "move", "--pane", pane, "--index", "0"], "tab_group.move"),
        (vec!["tab", "group", "g", "ungroup"], "tab_group.ungroup"),
        (vec!["tab", "group", "g", "close"], "tab_group.close"),
        (vec!["tab", "group", "saved", "list", "--room", "r"], "saved_tab_group.list"),
        (vec!["tab", "group", "g", "save", "--room", "r"], "saved_tab_group.save"),
        (vec!["tab", "group", "saved", "s", "reopen", "--pane", pane], "saved_tab_group.reopen"),
        (vec!["tab", "group", "saved", "s", "delete"], "saved_tab_group.delete"),
        (vec!["room", "list"], "room.list"),
        (
            vec![
                "room", "create", "--name", "n", "--color", "c", "--icon", "i", "--theme", "t",
                "--index", "0",
            ],
            "room.create",
        ),
        (
            vec![
                "room",
                "r",
                "update",
                "--name",
                "n",
                "--color",
                "c",
                "--icon",
                "i",
                "--theme",
                "t",
                "--browser-profile",
                "p",
                "--default-session",
                "s",
            ],
            "room.update",
        ),
        (vec!["room", "r", "delete", "--move-to", "r2"], "room.delete"),
        (vec!["room", "r", "move", "--index", "0"], "room.move"),
        (vec!["room", "r", "follow", "--sessions", "s1"], "room.follow"),
        (vec!["room", "r", "pin", "--workspace", workspace], "room.pin"),
        (vec!["room", "unpin", "--workspace", workspace], "room.unpin"),
        (
            vec!["screen", screen, "update", "--pinned", "true", "--color", "c", "--icon", "i"],
            "screen.update",
        ),
        (vec!["screen", screen, "move", "--index", "0"], "screen.move"),
        (vec!["screen", "group", "list", "--workspace", workspace], "screen_group.list"),
        (vec!["screen", "group", "g", "show"], "screen_group.get"),
        (
            vec![
                "screen",
                "group",
                "create",
                "--screens",
                screen,
                "--name",
                "n",
                "--color",
                "blue",
            ],
            "screen_group.create",
        ),
        (
            vec!["screen", "group", "g", "update", "--name", "n", "--color", "red", "--collapse"],
            "screen_group.update",
        ),
        (vec!["screen", "group", "g", "add", "--screens", screen], "screen_group.add_screens"),
        (vec!["screen", "group", "remove", "--screens", screen], "screen_group.remove_screens"),
        (vec!["screen", "group", "g", "ungroup"], "screen_group.ungroup"),
        (vec!["closed", "list"], "closed.list"),
        (vec!["closed", "c1", "reopen"], "closed.reopen"),
        (
            vec![
                "history",
                "search",
                "swift",
                "--kind",
                "page,agent",
                "--range",
                "week",
                "--limit",
                "5",
                "--local-day-start-ms",
                "1000",
            ],
            "history.entries.list",
        ),
        (vec!["history", "get", "page:default:1"], "history.entries.get"),
        (
            vec!["history", "remove", "page:default:1", "agent:local/claude/s"],
            "history.entries.remove",
        ),
        (
            vec!["history", "remove-site", "example.com", "--profile", "default"],
            "history.site.remove",
        ),
        (
            vec![
                "history",
                "clear-range",
                "--range",
                "today",
                "--kind",
                "page",
                "--profile",
                "default",
                "--local-day-start-ms",
                "1000",
                "--since-ms",
                "500",
            ],
            "history.clear",
        ),
        (
            vec!["history", "remove-url", "https://x/", "--profile", "default"],
            "history.visit.remove",
        ),
        (
            vec!["history", "summaries", "--profile", "default", "--limit", "10"],
            "history.visit.summaries",
        ),
        (vec!["workspace", workspace, "status", "list"], "workspace_status.list"),
        (
            vec!["workspace", workspace, "status", "set", "k", "t", "--icon", "i", "--color", "c"],
            "workspace_status.set",
        ),
        (vec!["workspace", workspace, "status", "clear", "k"], "workspace_status.clear"),
        (
            vec!["workspace", workspace, "progress", "set", "0.5", "--label", "l"],
            "workspace_progress.set",
        ),
        (vec!["workspace", workspace, "progress", "clear"], "workspace_progress.clear"),
        (
            vec!["workspace", workspace, "log", "append", "t", "--level", "info", "--source", "s"],
            "workspace_log.append",
        ),
        (vec!["workspace", workspace, "log", "list", "--limit", "5"], "workspace_log.list"),
        (vec!["workspace", workspace, "log", "clear"], "workspace_log.clear"),
    ]
}
